#!/bin/bash

set -euxo pipefail

if [[ "${EUID}" -eq 0 ]]; then
  echo 'ERROR: This script must NOT be run as root' >&2
  exit 1
fi

xvfb-run -a -s '-screen 0 1280x1024x24 -ac +extension GLX +extension RANDR +render -noreset' \
  bazel test //...
